# Site settings
title: "Alternativesec"
email: seceventspen@alternativesec.xyz
description: "A small website blog for cyber sec and pentesting adventures. "
baseurl: ""
url: "https://alternativesec.xyz"
title_description: "Looking at security from alternative means. I am self confessed cyber geek, who\'s passionate about strength and conditioning, functional movement and generally an all round awesome guy!
I Should have been in the Avengers, but it wouldn't have been fair on the others!
Any opinions expressed here are my own and not that of my employer."
title_image: "/img/Mask.jpg"
google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/Seceventspen/Alternativesec
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: SecEventsPen
github_username:  Seceventspen
# instagram_username:
# reddit_username:
# linkedin_link:
# google_plus_link:
# stackoverflow_link:
# xing_link:
# facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/SecEventsPen\">SecEventsPen</a>"
footer_right: "&lt;/&gt; on <a href=\"https://seceventspen.github.io/Alternativesec/\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
exclude: [README.md]
