# Site setings
name: "AlternativeSec"
description: "Looking at security from alternative means. I am a self confessed cyber geek, who's passionate about strength and conditioning, functional movement and generally an all round awesome guy!\ I Should have been in the Avengers, but it wouldn't have been fair on the others!"
meta_description: "Jekyll template, minimal style, perfect for bloggers."
logo: "/assets/images/logoAS.png"
favicon: "assets/images/favicon.ico"
baseurl:
production_url: https://alternativesec.xyz
disqus:
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
cover_image: bc_1.jpg
# Add your GA Tracking Id
#ga_analytics:

# Author
author:
  name: "Spence"
  image: "authorimage1.jpg"
  greetings: "Hi there!"
  description: "My name is Spence. I'm an adverserial engineer, hax0r of life and things, based out of the Emerald Isle. It’s nice to meet you!"
  bio: "Spence is a penetration tester, with a curious mind, who looks to give back to the community that has given so much to him. He's a speaker, when asked, and a fulltime father. Join him in his security adventures, along with his musings on projects, write-ups, various security topics, fitness and beyond."

# Contact form setings
email: crtlaltdel@alternativesec.xyz
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: "@SecEventsPen"
#facebook: "username"
github: "SecEventsPen"
#codepen: "username"
#dribbble: "username"
#medium: "@username"
#instagram: "username"
#pinterest: "username"
linkedin: "steve-spence-no-recruiters-please"
#producthunt: "@username"

# Navigation
navigation:
  - text: About
    url: /about
  - text: Archive
    url: /tags
  #- text: Style Guide
  #  url: /style-guide
  #- text: Password Generator
  #  url: /password-generator

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
